version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    groups:
      argosci:
        applies-to: version-updates
        patterns:
          - "@argos-ci/*"
      storybook:
        applies-to: version-updates
        patterns:
          - "@storybook/*"
          - "storybook"
          - "storybook-dark-mode"
      commitlint:
        applies-to: version-updates
        patterns:
          - "@commitlint/*"
      eslint:
        applies-to: version-updates
        patterns:
          - "eslint"
          - "@eslint/*"
      typescript-eslint:
        applies-to: version-updates
        patterns:
          - "@typescript-eslint/*"
          - "typescript-eslint"
      vitest:
        applies-to: version-updates
        patterns:
          - "@vitest/*"
          - "vitest"
      typedoc:
        applies-to: version-updates
        patterns:
          - "typedoc"
          - "typedoc-plugin-markdown"
          - "docusaurus-plugin-typedoc"
      vue:
        applies-to: version-updates
        patterns:
          - "vue"
          - "@vue/*"
          - "vue-router"
          - "vuex"
          - "vite-plugin-vue2"
          - "vite-plugin-vue3"
